"""empty message

Revision ID: 6765c0c25c68
Revises: 1b8f72f551bc
Create Date: 2018-10-28 16:23:41.028351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6765c0c25c68'
down_revision = '1b8f72f551bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'rating')
    # ### end Alembic commands ###
